trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
- group: sonar-key
- name: pythonVersion
  value: '3.9'

steps:

# 1️⃣ Use Python version
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(pythonVersion)'
    addToPath: true

# 2️⃣ Install dependencies
- script: |
    python -m pip install --upgrade pip
    if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    pip install pytest pytest-cov
  displayName: 'Install dependencies'

# 3️⃣ Run tests with coverage
- script: |
    pytest --cov=. --cov-report=xml
  displayName: 'Run Tests'

# 4️⃣ Prepare SonarQube Analysis
- task: SonarQubePrepare@8
  inputs:
    SonarQube: 'sonar-connection'
    scannerMode: 'CLI'
    configMode: 'manual'
    cliProjectKey: '${sonar-python}'
    cliProjectName: 'spring-petclinic'
    cliSources: '.'

# 5️⃣ Run SonarQube Scan
- task: SonarQubeAnalyze@8


# 6️⃣ Publish SonarQube Result (Quality Gate)
- task: SonarQubePublish@8
  inputs:
    pollingTimeoutSec: '300'